### ISSUE TITLE
Won't compile with stack

### ISSUE THREAD

**Issue by tittoassini** [mstksg/ghcjs-websockets#10]
Hi,

I am trying to write a package that uses websockets while being compatible with both ghc and ghcjs.

For the ghcjs part I am using ghcjs-websockets.

I would like the package to be buildable with stack but unfortunately when building for ghc, I get:

stack install ghcjs-websockets 

--  While attempting to add dependency,
    Could not find package ghcjs-base in known packages

--  Failure when adding dependencies:  
      ghcjs-base: needed (>=0.1), stack configuration has no specified version
    needed for package ghcjs-websockets-0.3.0.5

**Comment by mstksg** [comment]
Hi!

I've been meaning to update the front page with information on this.   ghcjs now offers native websockets, in ghcjs-base...so for basic websockets functionality, you don't need any extra packages.  There is some missing functionality (being able to send binary, non-text data) in ghcjs-base that this library (used to) have.  I'm planning on re-integrating the features into ghcjs-base rather than updating this library, and deprecating it.

So -- you might not need this package at all, just use ghcjs's native websockets :)  if you need to use binary data, let me know and I'll walk you through getting temporary compatibility.

**Comment by tittoassini** [comment]
Thanks for the answer.

I am now trying to use ghcjs-base.

There seems to be support for binary communication in ghcjs-base actually, but I am having trouble using it, I am lost in the maze of Haskell-JS type conversions :-(

I manage to send binary data but I am not able to read it from incoming messages.

Messages are returned as MessageEvent objects.

I try to extract a binary message from the ArrayBufferData constructor using something like:
ArrayBufferData ab -> Buffer.toByteString 0 Nothing . Buffer.createFromArrayBuffer $ ab

But I get an error: uncaught exception in Haskell thread: h$wrapBuffer: not an ArrayBuffer

I know that this has nothing to do with your software, but if, having worked with ghcjs, you could immediately spot what the problem is, your advice would be very welcome.

**Comment by tittoassini** [comment]
It seems that the problem was caused by this:

https://github.com/ghcjs/ghcjs-base/issues/60

For which there has been a PR standing for months ...

So I will close this issue now, all the best.

**Comment by mstksg** [comment]
Glad there is light at the end of the tunnel here, thanks for bringing this all to my attention.  Best of luck moving forward!
